// Generated by CoffeeScript 1.8.0
var ConfigLoader, YAML;

YAML = require('yamljs');

ConfigLoader = (function() {
  var CONFIGURATION_FILE_PATH;

  function ConfigLoader() {}

  CONFIGURATION_FILE_PATH = "./conf/application.yml";

  ConfigLoader.loadFor = function(environment, configFilePath) {
    var configurations;
    if (configFilePath == null) {
      configFilePath = CONFIGURATION_FILE_PATH;
    }
    configurations = this._loadFile(configFilePath);
    return this._readFor({
      environment: environment,
      configurations: configurations
    });
  };

  ConfigLoader._readFor = function(_arg) {
    var configurations, environment;
    environment = _arg.environment, configurations = _arg.configurations;
    if (configurations[environment] != null) {
      return configurations[environment];
    } else {
      throw "Could not find configuration for " + environment + " environment";
    }
  };

  ConfigLoader._loadFile = function(filePath) {
    return YAML.load(filePath);
  };

  return ConfigLoader;

})();

module.exports = ConfigLoader;
